
function capabilityToAttributeMap() {
    return {
    "accelerationsensor": ["acceleration"],
    "alarm": ["alarm"],
    "audiovolume": ["mute","volume"],
    "battery": ["battery"],
    "beacon": ["presence"],
    "bulb": ["switch"],
    "button": ["button","holdableButton","numberOfButtons"],
    "carbondioxidemeasurement": ["carbonDioxide"],
    "carbonmonoxidedetector": ["carbonMonoxide"],
    "chime": ["soundEffects","soundName","status"],
    "colorcontrol": ["RGB","color","colorName","hue","saturation"],
    "colormode": ["colorMode"],
    "colortemperature": ["colorName","colorTemperature"],
    "consumable": ["consumableStatus"],
    "contactsensor": ["contact"],
    "doorcontrol": ["door"],
    "doubletapablebutton": ["doubleTapped"],
    "energymeter": ["energy"],
    "estimatedtimeofarrival": ["eta"],
    "fancontrol": ["speed"],
    "filterstatus": ["filterStatus"],
    "garagedoorcontrol": ["door"],
    "healthcheck": ["checkInterval"],
    "holdablebutton": ["held"],
    "illuminancemeasurement": ["illuminance"],
    "imagecapture": ["image"],
    "indicator": ["indicatorStatus"],
    "light": ["switch"],
    "lighteffects": ["effectName","lightEffects"],
    "locationmode": ["mode"],
    "lock": ["lock"],
    "lockcodes": ["codeChanged","codeLength","lockCodes","maxCodes"],
    "mediacontroller": ["activities","currentActivity"],
    "motionsensor": ["motion"],
    "musicplayer": ["level","mute","status","trackData","trackDescription"],
    "outlet": ["switch"],
    "powermeter": ["power"],
    "powersource": ["powerSource"],
    "presencesensor": ["presence"],
    "pressuremeasurement": ["pressure"],
    "pushablebutton": ["numberOfButtons","pushed"],
    "relativehumiditymeasurement": ["humidity"],
    "relayswitch": ["switch"],
    "releasablebutton": ["released"],
    "samsungtv": ["messageButton","mute","pictureMode","soundMode","switch","volume"],
    "securitykeypad": ["codeChanged","codeLength","lockCodes","maxCodes","securityKeypad"],
    "shocksensor": ["shock"],
    "signalstrength": ["lqi","rssi"],
    "sleepsensor": ["sleeping"],
    "smokedetector": ["smoke"],
    "soundpressurelevel": ["soundPressureLevel"],
    "soundsensor": ["sound"],
    "speechrecognition": ["phraseSpoken"],
    "stepsensor": ["goal","steps"],
    "switch": ["switch"],
    "switchlevel": ["level"],
    "tv": ["channel","movieMode","picture","power","sound","volume"],
    "tamperalert": ["tamper"],
    "temperaturemeasurement": ["temperature"],
    "thermostat": ["coolingSetpoint","heatingSetpoint","schedule","supportedThermostatFanModes","supportedThermostatModes","temperature","thermostatFanMode","thermostatMode","thermostatOperatingState","thermostatSetpoint"],
    "thermostatcoolingsetpoint": ["coolingSetpoint"],
    "thermostatfanmode": ["thermostatFanMode"],
    "thermostatheatingsetpoint": ["heatingSetpoint"],
    "thermostatmode": ["thermostatMode"],
    "thermostatoperatingstate": ["thermostatOperatingState"],
    "thermostatschedule": ["schedule"],
    "thermostatsetpoint": ["thermostatSetpoint"],
    "threeaxis": ["threeAxis"],
    "timedsession": ["sessionStatus","timeRemaining"],
    "touchsensor": ["touch"],
    "ultravioletindex": ["ultravioletIndex"],
    "valve": ["valve"],
    "videocapture": ["camera","mute","settings","statusMessage"],
    "videocapture": ["clip"],
    "voltagemeasurement": ["voltage"],
    "watersensor": ["water"],
    "windowshade": ["position","windowShade"],
    "zwmultichannel": ["epEvent","epInfo"],
    "phmeasurement": ["pH"]
    };    
}
module.exports = {
        capabilityToAttributeMap: capabilityToAttributeMap
    }



